name: youtube_upload
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC
    - cron: '0 8 * * *'   # 08:00 UTC
    - cron: '0 16 * * *'  # 16:00 UTC
    - cron: '0 20 * * *'  # 16:00 UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


      - name: Run main_app
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

        run: |
          python main_app.py
  notify-on-failure:
    name: Notify Discord on Failure
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"🚨 GitHub Action failed in repo: ${{ github.repository }}\nWorkflow: ${{ github.workflow }}\nBranch: ${{ github.ref_name }}\n🔗 <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}